
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ilham
 */
public class form_utama extends javax.swing.JFrame {

    double val1, val2, hasil;
    String text = "";
    String cektext = "";
    String angka = "";
    boolean hitung = false;
    boolean operator = false;
    char charOperator;

    /**
     * Creates new form form_utama
     */
    public form_utama() {
        initComponents();
        
        txt_tampilan.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_tampilan = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_hasil = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_kurang = new javax.swing.JButton();
        btn_bagi = new javax.swing.JButton();
        btn_kali = new javax.swing.JButton();
        lbl_perhitungan = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_koma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        jLabel1.setText("Calculator");

        txt_tampilan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tampilan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tampilanKeyReleased(evt);
            }
        });

        btn_tambah.setText("+");
        btn_tambah.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_tambah.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_tambah.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hasil.setText("=");
        btn_hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hasilActionPerformed(evt);
            }
        });

        btn_7.setText("7");
        btn_7.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_7.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_7.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_4.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_4.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_1.setText("1");
        btn_1.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_1.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_1.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_8.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_8.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_5.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_5.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_2.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_2.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_9.setText("9");
        btn_9.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_9.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_9.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_6.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_6.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_3.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_3.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_0.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_0.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_clear.setText("C");
        btn_clear.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_clear.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_clear.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_kurang.setText("-");
        btn_kurang.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_kurang.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_kurang.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kurangActionPerformed(evt);
            }
        });

        btn_bagi.setText("/");
        btn_bagi.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_bagi.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_bagi.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bagiActionPerformed(evt);
            }
        });

        btn_kali.setText("*");
        btn_kali.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_kali.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_kali.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaliActionPerformed(evt);
            }
        });

        btn_hapus.setText("<-");
        btn_hapus.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_hapus.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_hapus.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_koma.setText(".");
        btn_koma.setMaximumSize(new java.awt.Dimension(45, 30));
        btn_koma.setMinimumSize(new java.awt.Dimension(45, 30));
        btn_koma.setPreferredSize(new java.awt.Dimension(45, 30));
        btn_koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_komaActionPerformed(evt);
            }
        });

        jLabel2.setText("Dibuat oleh : Moch Ilham Fauzan - 10118246 - IF06");

        jLabel3.setText("v 1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_tampilan)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_koma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_kali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_tambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_bagi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_hapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_perhitungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_perhitungan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tampilan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_kali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_bagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_koma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        if (operator == false) {
            text += "+";
            txt_tampilan.setText(text);
            operator = true;
            charOperator = '+';
            angka = "";
        } else {
            if (charOperator == '+') {
                hasil = val1 + val2;
            } else if (charOperator == '-') {
                hasil = val1 - val2;
            } else if (charOperator == '*') {
                hasil = val1 * val2;
            } else if (charOperator == '/') {
                hasil = val1 / val2;
            }
            charOperator = '+';
            val1 = hasil;
            val2 = 0;
            lbl_perhitungan.setText(text);
            txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
            text = "";
            angka = "";
        }
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hasilActionPerformed
        // TODO add your handling code here:

        if (operator == true) {
            if (charOperator == '+') {
                hasil = val1 + val2;
            } else if (charOperator == '-') {
                hasil = val1 - val2;
            } else if (charOperator == '*') {
                hasil = val1 * val2;
            } else if (charOperator == '/') {
                hasil = val1 / val2;
            }
            val1 = hasil;
            lbl_perhitungan.setText(text);
            txt_tampilan.setText(String.format("%.2f", hasil));
            operator = false;
            text = "";
        }
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_hasilActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "1";
        angka += "1";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "0";
        angka += "0";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "2";
        angka += "2";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "3";
        angka += "3";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "4";
        angka += "4";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "5";
        angka += "5";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "6";
        angka += "6";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "7";
        angka += "7";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "8";
        angka += "8";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        text += "9";
        angka += "9";
        if (operator == false) {
            val1 = Double.valueOf(angka);
        } else {
            val2 = Double.valueOf(angka);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        text = "";
        angka = "";
        val1 = 0;
        val2 = 0;
        operator = false;
        charOperator = ' ';
        txt_tampilan.setText(text);
        lbl_perhitungan.setText(text);
        txt_tampilan.requestFocus();

    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_tampilanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tampilanKeyReleased
        // TODO add your handling code here:
        char operator_ke1 = ' ';
        String mystr = "";
        text = txt_tampilan.getText();
        int myint = text.length() - 1;
        if (myint >= 0) {
            char mychar = text.charAt(myint);

            if (mychar == '1' || mychar == '2' || mychar == '3' || mychar == '4' || mychar == '5'
                    || mychar == '6' || mychar == '7' || mychar == '8' || mychar == '9' || mychar == '0'
                    || mychar == '.' || mychar == '+' || mychar == '-' || mychar == '/' || mychar == '*'
                    || mychar == '=') {
                try {

                    operator = false;
                    angka = "";
                    for (int i = 0; i <= myint; i++) {
                        mychar = text.charAt(i);
                        if (operator == false) {
                            if (mychar == '1' || mychar == '2' || mychar == '3' || mychar == '4' || mychar == '5'
                                    || mychar == '6' || mychar == '7' || mychar == '8' || mychar == '9' || mychar == '0'
                                    || mychar == '.') {
                                angka += mychar;
                                val1 = Double.valueOf(angka);
                            } else if (mychar == '+') {
                                operator = true;
                                charOperator = '+';
                                operator_ke1 = '+';
                                angka = "";
                            } else if (mychar == '-') {
                                operator = true;
                                charOperator = '-';
                                operator_ke1 = '-';
                                angka = "";
                            } else if (mychar == '*') {
                                operator = true;
                                charOperator = '*';
                                operator_ke1 = '*';
                                angka = "";
                            } else if (mychar == '/') {
                                operator = true;
                                charOperator = '/';
                                operator_ke1 = '/';
                                angka = "";
                            } else if (mychar == '=') {
                                operator = true;
                                angka = "";
                            }
                        } else {
                            if (mychar == '1' || mychar == '2' || mychar == '3' || mychar == '4' || mychar == '5'
                                    || mychar == '6' || mychar == '7' || mychar == '8' || mychar == '9' || mychar == '0'
                                    || mychar == '=' || mychar == '.') {
                                if (mychar == '=') {
                                    txt_tampilan.setText(" ");
                                    if (operator_ke1 == '+') {
                                        hasil = val1 + val2;
                                    } else if (operator_ke1 == '-') {
                                        hasil = val1 - val2;
                                    } else if (operator_ke1 == '*') {
                                        hasil = val1 * val2;
                                    } else if (operator_ke1 == '/') {
                                        hasil = val1 / val2;
                                    }
                                    for (int j = 0; j <= text.length() - 2; j++) {
                                        mystr += text.charAt(j);

                                    }
                                    lbl_perhitungan.setText(mystr);
                                    txt_tampilan.setText(String.format("%.2f", hasil));

                                } else if (mychar == '.') {
                                    angka += mychar;
                                } else {
                                    angka += mychar;
                                    val2 = Double.valueOf(angka);
                                }
                            } else if (mychar == '+') {
                                txt_tampilan.setText(" ");
                                if (operator_ke1 == '+') {
                                    hasil = val1 + val2;
                                } else if (operator_ke1 == '-') {
                                    hasil = val1 - val2;
                                } else if (operator_ke1 == '*') {
                                    hasil = val1 * val2;
                                } else if (operator_ke1 == '/') {
                                    hasil = val1 / val2;
                                }
                                charOperator = '+';
                                for (int j = 0; j <= text.length() - 2; j++) {
                                    mystr += text.charAt(j);

                                }
                                lbl_perhitungan.setText(mystr);
                                txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
                            } else if (mychar == '-') {
                                txt_tampilan.setText(" ");
                                if (operator_ke1 == '+') {
                                    hasil = val1 + val2;
                                } else if (operator_ke1 == '-') {
                                    hasil = val1 - val2;
                                } else if (operator_ke1 == '*') {
                                    hasil = val1 * val2;
                                } else if (operator_ke1 == '/') {
                                    hasil = val1 / val2;
                                }

                                charOperator = '-';
                                for (int j = 0; j <= text.length() - 2; j++) {
                                    mystr += text.charAt(j);

                                }
                                lbl_perhitungan.setText(mystr);
                                txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
                            } else if (mychar == '*') {
                                txt_tampilan.setText(" ");
                                if (operator_ke1 == '+') {
                                    hasil = val1 + val2;
                                } else if (operator_ke1 == '-') {
                                    hasil = val1 - val2;
                                } else if (operator_ke1 == '*') {
                                    hasil = val1 * val2;
                                } else if (operator_ke1 == '/') {
                                    hasil = val1 / val2;
                                }
                                charOperator = '*';
                                for (int j = 0; j <= text.length() - 2; j++) {
                                    mystr += text.charAt(j);

                                }
                                lbl_perhitungan.setText(mystr);
                                txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
                            } else if (mychar == '/') {
                                txt_tampilan.setText(" ");
                                if (operator_ke1 == '+') {
                                    hasil = val1 + val2;
                                } else if (operator_ke1 == '-') {
                                    hasil = val1 - val2;
                                } else if (operator_ke1 == '*') {
                                    hasil = val1 * val2;
                                } else if (operator_ke1 == '/') {
                                    hasil = val1 / val2;
                                }

                                charOperator = '/';
                                for (int j = 0; j <= text.length() - 2; j++) {
                                    mystr += text.charAt(j);

                                }
                                lbl_perhitungan.setText(mystr);
                                txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
                            }
                        }
                    }

                } catch (Exception e) {
                    if (myint <= 0) {
                        txt_tampilan.setText(" ");
                    } else {
                        if (text.charAt(myint) == '.') {
                            mystr = "";
                            for (int i = 0; i < myint; i++) {
                                mystr += text.charAt(i);
                            }
                            txt_tampilan.setText(mystr);
                        }
                    }
                }
            } else {
                for (int j = 0; j <= text.length() - 2; j++) {
                    mystr += text.charAt(j);
                }
                txt_tampilan.setText(mystr);
            }
        }
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_txt_tampilanKeyReleased

    private void btn_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kurangActionPerformed
        // TODO add your handling code here: 
        text = txt_tampilan.getText();
        if (operator == false) {
            text += "-";
            txt_tampilan.setText(text);
            charOperator = '-';
            operator = true;
            angka = "";
        } else {
            if (charOperator == '+') {
                hasil = val1 + val2;
            } else if (charOperator == '-') {
                hasil = val1 - val2;
            } else if (charOperator == '*') {
                hasil = val1 * val2;
            } else if (charOperator == '/') {
                hasil = val1 / val2;
            }
            charOperator = '-';
            val1 = hasil;
            val2 = 0;
            lbl_perhitungan.setText(text);
            txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
            text = "";
            angka = "";
        }
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_kurangActionPerformed

    private void btn_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaliActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        if (operator == false) {
            text += "*";
            txt_tampilan.setText(text);
            operator = true;
            charOperator = '*';
            angka = "";
        } else {
            if (charOperator == '+') {
                hasil = val1 + val2;
            } else if (charOperator == '-') {
                hasil = val1 - val2;
            } else if (charOperator == '*') {
                hasil = val1 * val2;
            } else if (charOperator == '/') {
                hasil = val1 / val2;
            }
            charOperator = '*';
            val1 = hasil;
            val2 = 0;
            lbl_perhitungan.setText(text);
            txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
            text = "";
            angka = "";
        }
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_kaliActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
 
        text = txt_tampilan.getText();
        String mystr = "";
        char mychar;
        int myint = text.length() - 1;
        if (myint >0) {
            for (int i = 0; i < myint; i++) {
                mychar = text.charAt(i);
                mystr += mychar;
            }
            txt_tampilan.setText(mystr);
        } else {
            text = "";
            txt_tampilan.setText(text);
            lbl_perhitungan.setText(text);
            angka = "";
            val1 = 0;
            val2 = 0;
            charOperator = ' ';
            operator = false;
        }
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bagiActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        if (operator == false) {
            text += "/";
            txt_tampilan.setText(text);
            operator = true;
            charOperator = '/';
            angka = "";
        } else {
            if (charOperator == '+') {
                hasil = val1 + val2;
            } else if (charOperator == '-') {
                hasil = val1 - val2;
            } else if (charOperator == '*') {
                hasil = val1 * val2;
            } else if (charOperator == '/') {
                hasil = val1 / val2;
            }
            charOperator = '/';
            val1 = hasil;
            val2 = 0;
            lbl_perhitungan.setText(text);
            txt_tampilan.setText(String.format("%.2f", hasil) + charOperator);
            text = "";
            angka = "";
        }
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_bagiActionPerformed

    private void btn_komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_komaActionPerformed
        // TODO add your handling code here:
        text = txt_tampilan.getText();
        try {
            if (operator == false) {

                val1 = Double.valueOf(text + ".");
            } else {
                val2 = Double.valueOf(text + ".");
            }
            angka += ".";
            text += ".";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txt_tampilan.setText(text);
        txt_tampilan.requestFocus();
    }//GEN-LAST:event_btn_komaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_utama().setVisible(true);
                JOptionPane.showMessageDialog(null, "SELAMAT DATANG \nAnda dapat memasukkan nilai dan operator melalui keyboard maupun melalui tombol yang sudah tersedia");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_bagi;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hasil;
    private javax.swing.JButton btn_kali;
    private javax.swing.JButton btn_koma;
    private javax.swing.JButton btn_kurang;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_perhitungan;
    private javax.swing.JTextField txt_tampilan;
    // End of variables declaration//GEN-END:variables

}
